# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import a2a_session_pb2 as a2a__session__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in a2a_session_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class A2ADatingServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitiateSession = channel.unary_unary(
                '/a2a.A2ADatingService/InitiateSession',
                request_serializer=a2a__session__pb2.InitiateRequest.SerializeToString,
                response_deserializer=a2a__session__pb2.InitiateResponse.FromString,
                _registered_method=True)
        self.StreamDebate = channel.stream_stream(
                '/a2a.A2ADatingService/StreamDebate',
                request_serializer=a2a__session__pb2.DebateTurn.SerializeToString,
                response_deserializer=a2a__session__pb2.DebateTurn.FromString,
                _registered_method=True)
        self.StreamFullDebate = channel.unary_stream(
                '/a2a.A2ADatingService/StreamFullDebate',
                request_serializer=a2a__session__pb2.InitiateRequest.SerializeToString,
                response_deserializer=a2a__session__pb2.DebateTurn.FromString,
                _registered_method=True)
        self.SubmitMatchDecision = channel.unary_unary(
                '/a2a.A2ADatingService/SubmitMatchDecision',
                request_serializer=a2a__session__pb2.MatchDecision.SerializeToString,
                response_deserializer=a2a__session__pb2.MatchResult.FromString,
                _registered_method=True)


class A2ADatingServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def InitiateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamDebate(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamFullDebate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitMatchDecision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_A2ADatingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitiateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.InitiateSession,
                    request_deserializer=a2a__session__pb2.InitiateRequest.FromString,
                    response_serializer=a2a__session__pb2.InitiateResponse.SerializeToString,
            ),
            'StreamDebate': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamDebate,
                    request_deserializer=a2a__session__pb2.DebateTurn.FromString,
                    response_serializer=a2a__session__pb2.DebateTurn.SerializeToString,
            ),
            'StreamFullDebate': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamFullDebate,
                    request_deserializer=a2a__session__pb2.InitiateRequest.FromString,
                    response_serializer=a2a__session__pb2.DebateTurn.SerializeToString,
            ),
            'SubmitMatchDecision': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitMatchDecision,
                    request_deserializer=a2a__session__pb2.MatchDecision.FromString,
                    response_serializer=a2a__session__pb2.MatchResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'a2a.A2ADatingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('a2a.A2ADatingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class A2ADatingService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitiateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.A2ADatingService/InitiateSession',
            a2a__session__pb2.InitiateRequest.SerializeToString,
            a2a__session__pb2.InitiateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamDebate(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/a2a.A2ADatingService/StreamDebate',
            a2a__session__pb2.DebateTurn.SerializeToString,
            a2a__session__pb2.DebateTurn.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamFullDebate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/a2a.A2ADatingService/StreamFullDebate',
            a2a__session__pb2.InitiateRequest.SerializeToString,
            a2a__session__pb2.DebateTurn.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitMatchDecision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/a2a.A2ADatingService/SubmitMatchDecision',
            a2a__session__pb2.MatchDecision.SerializeToString,
            a2a__session__pb2.MatchResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
