# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: a2a_session.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'a2a_session.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import avatar_pb2 as avatar__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x61\x32\x61_session.proto\x12\x03\x61\x32\x61\x1a\x0c\x61vatar.proto\"\x9c\x01\n\x0fInitiateRequest\x12+\n\x0cself_capsule\x18\x01 \x01(\x0b\x32\x15.avatar.AvatarCapsule\x12+\n\x0cpeer_capsule\x18\x02 \x01(\x0b\x32\x15.avatar.AvatarCapsule\x12\x11\n\ttopic_ids\x18\x03 \x03(\t\x12\x1c\n\x14max_rounds_per_topic\x18\x04 \x01(\x05\"I\n\x10InitiateResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x7f\n\nDebateTurn\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x10\n\x08topic_id\x18\x02 \x01(\t\x12\r\n\x05round\x18\x03 \x01(\x05\x12\x19\n\x11speaker_avatar_id\x18\x04 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x05 \x01(\t\x12\x10\n\x08is_final\x18\x06 \x01(\x08\"I\n\rMatchDecision\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x11\n\tavatar_id\x18\x02 \x01(\t\x12\x11\n\tconfirmed\x18\x03 \x01(\x08\"`\n\x0bMatchResult\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0f\n\x07matched\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t\x12\x1b\n\x13\x63ompatibility_score\x18\x04 \x01(\x01\x32\x82\x02\n\x10\x41\x32\x41\x44\x61tingService\x12>\n\x0fInitiateSession\x12\x14.a2a.InitiateRequest\x1a\x15.a2a.InitiateResponse\x12\x34\n\x0cStreamDebate\x12\x0f.a2a.DebateTurn\x1a\x0f.a2a.DebateTurn(\x01\x30\x01\x12;\n\x10StreamFullDebate\x12\x14.a2a.InitiateRequest\x1a\x0f.a2a.DebateTurn0\x01\x12;\n\x13SubmitMatchDecision\x12\x12.a2a.MatchDecision\x1a\x10.a2a.MatchResultb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'a2a_session_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INITIATEREQUEST']._serialized_start=41
  _globals['_INITIATEREQUEST']._serialized_end=197
  _globals['_INITIATERESPONSE']._serialized_start=199
  _globals['_INITIATERESPONSE']._serialized_end=272
  _globals['_DEBATETURN']._serialized_start=274
  _globals['_DEBATETURN']._serialized_end=401
  _globals['_MATCHDECISION']._serialized_start=403
  _globals['_MATCHDECISION']._serialized_end=476
  _globals['_MATCHRESULT']._serialized_start=478
  _globals['_MATCHRESULT']._serialized_end=574
  _globals['_A2ADATINGSERVICE']._serialized_start=577
  _globals['_A2ADATINGSERVICE']._serialized_end=835
# @@protoc_insertion_point(module_scope)
