# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: avatar.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'avatar.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x61vatar.proto\x12\x06\x61vatar\"~\n\rBigFiveScores\x12\x10\n\x08openness\x18\x01 \x01(\x01\x12\x19\n\x11\x63onscientiousness\x18\x02 \x01(\x01\x12\x14\n\x0c\x65xtraversion\x18\x03 \x01(\x01\x12\x15\n\ragreeableness\x18\x04 \x01(\x01\x12\x13\n\x0bneuroticism\x18\x05 \x01(\x01\"\x84\x01\n\x13\x45motionDistribution\x12\x0b\n\x03joy\x18\x01 \x01(\x01\x12\x0f\n\x07sadness\x18\x02 \x01(\x01\x12\r\n\x05\x61nger\x18\x03 \x01(\x01\x12\x0c\n\x04\x66\x65\x61r\x18\x04 \x01(\x01\x12\x10\n\x08surprise\x18\x05 \x01(\x01\x12\x0f\n\x07\x64isgust\x18\x06 \x01(\x01\x12\x0f\n\x07neutral\x18\x07 \x01(\x01\"#\n\x11PersonalityVector\x12\x0e\n\x06values\x18\x01 \x03(\x01\"Q\n\x15\x42\x65havioralFingerprint\x12\x0c\n\x04hash\x18\x01 \x01(\x0c\x12\x14\n\x0cwindow_count\x18\x02 \x01(\x03\x12\x14\n\x0clast_updated\x18\x03 \x01(\x03\"\x9b\x02\n\rAvatarCapsule\x12\x11\n\tavatar_id\x18\x01 \x01(\t\x12)\n\x06vector\x18\x02 \x01(\x0b\x32\x19.avatar.PersonalityVector\x12\'\n\x08\x62ig_five\x18\x03 \x01(\x0b\x32\x15.avatar.BigFiveScores\x12\x30\n\x0b\x61vg_emotion\x18\x04 \x01(\x0b\x32\x1b.avatar.EmotionDistribution\x12\x32\n\x0b\x66ingerprint\x18\x05 \x01(\x0b\x32\x1d.avatar.BehavioralFingerprint\x12\x14\n\x0cslm_endpoint\x18\x06 \x01(\t\x12\x12\n\ncreated_at\x18\x07 \x01(\x03\x12\x13\n\x0b\x64rift_delta\x18\x08 \x01(\x01\"\x8c\x02\n\x0cPendingMatch\x12\x10\n\x08match_id\x18\x01 \x01(\t\x12+\n\x0cself_capsule\x18\x02 \x01(\x0b\x32\x15.avatar.AvatarCapsule\x12,\n\rother_capsule\x18\x03 \x01(\x0b\x32\x15.avatar.AvatarCapsule\x12\x1b\n\x13\x63ompatibility_score\x18\x04 \x01(\x01\x12\x19\n\x11\x61nonymized_report\x18\x05 \x01(\t\x12\x16\n\x0eself_confirmed\x18\x06 \x01(\x08\x12\x17\n\x0fother_confirmed\x18\x07 \x01(\x08\x12\x12\n\ncreated_at\x18\x08 \x01(\x03\x12\x12\n\nexpires_at\x18\t \x01(\x03\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'avatar_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BIGFIVESCORES']._serialized_start=24
  _globals['_BIGFIVESCORES']._serialized_end=150
  _globals['_EMOTIONDISTRIBUTION']._serialized_start=153
  _globals['_EMOTIONDISTRIBUTION']._serialized_end=285
  _globals['_PERSONALITYVECTOR']._serialized_start=287
  _globals['_PERSONALITYVECTOR']._serialized_end=322
  _globals['_BEHAVIORALFINGERPRINT']._serialized_start=324
  _globals['_BEHAVIORALFINGERPRINT']._serialized_end=405
  _globals['_AVATARCAPSULE']._serialized_start=408
  _globals['_AVATARCAPSULE']._serialized_end=691
  _globals['_PENDINGMATCH']._serialized_start=694
  _globals['_PENDINGMATCH']._serialized_end=962
# @@protoc_insertion_point(module_scope)
